In [1]:
#importing Numpy
import numpy as np

In [2]:
from time import process_time

In [3]:
# time taken by list
list1 = [i for i in range(10000000)]
start_time = process_time()
list1 = [i+10 for i in list1] #adding five to each number
end_time = process_time()
print(end_time-start_time)

1.125


In [4]:
array1 = np.array([i for i in range(10000000)])
start_time = process_time()
array1 += 10
end_time = process_time()
print(end_time-start_time)

0.015625


#### Conclusion :--> required time for operation with array is very less thats why we prefer to array against list or tuple.

In [5]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


- numeber are seperated by commas

In [6]:
Array1 = np.array([1,2,3,4,5])
print(Array1)
print(type(Array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- number of are not seperated by commas

## Built in function in Numpy Array
## Creating one dimentional array

In [7]:
# arange function
x = np.arange(1,10,2) # from 1 to 10 with step size 2
print(x)

[1 3 5 7 9]


In [8]:
# five random values from zero to one
x=np.random.rand(5)
print(x)

[0.07300832 0.88391953 0.04772143 0.34838327 0.75961367]


## Creating two dimentional array

In [9]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(list1)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 2*3 matrix contain from zero to one
x=np.random.rand(2,3)
print(x)

[[0.47253113 0.36158816 0.84992541]
 [0.08635288 0.36864389 0.03840046]]


In [11]:
#random values follows std normal distribution means whose mean is zero and std dev is 1
x = np.random.randn(5)
print(x)

[ 0.03988239 -0.24766981  1.71029175  0.37764059 -1.25006353]


In [12]:
# random values follows std normal distribution means whose mean is zero and std dev is 1
x=np.random.randn(3,4)
print(x)

[[-1.10485501 -0.09636671 -0.66343729  0.07111683]
 [ 0.94049366  0.42332458  1.36966485  0.2110586 ]
 [-0.00739175 -0.0062378   0.12665587 -0.19373729]]


In [13]:
#np.random.randint
x=np.random.randint(10,100,(3,4))
print(x)

[[16 41 35 35]
 [72 92 55 53]
 [71 88 30 76]]


In [14]:
# now create two dimentional array (with defining values at float values)
array2=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(array2)
array2.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

## Three dimentional array

In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## higher Dimentional arrays

In [16]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector,
the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and
1st dim has 1 element that is a 4D array.

## intial placeholder in numpy array

In [17]:
# create numpy array with all the values are zero
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# create numpy array with all the values are one
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# array of perticular values
x=np.full((4,4),5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [20]:
# creating identity matrix- all the diogonal element will be one and rest all the values 
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# create array with random values
x=np.random.random((3,4))
print(x)

[[0.26047351 0.59713824 0.15616444 0.41672586]
 [0.4232413  0.1188952  0.74494826 0.79226738]
 [0.70899618 0.11672829 0.54877322 0.40710021]]


- All the values you will get here will be in the range of 0 to 1

In [22]:
# create random int values
x=np.random.randint(10,100,(3,4))
print(x)

[[65 95 74 61]
 [26 89 77 16]
 [95 94 54 72]]


In [23]:
# creating array of evenly spaced values
x=np.linspace(10,30,5)
print(x)

[10. 15. 20. 25. 30.]


In [24]:
# converting list to array
list1=[10,20,30,40,50]
array1=np.asarray(list1)
print(array1)
type(array1)

[10 20 30 40 50]


numpy.ndarray

In [25]:
# converting tuple to array
tuple1=(10,20,30,40,50)
array1=np.asarray(tuple1)
print(array1)
type(array1)

[10 20 30 40 50]


numpy.ndarray

## Analysing numpy array

In [26]:
# shape of the array
x=np.random.randint(10,99,(4,5))
print(x)
print(f"Shape of the array:\n {x.shape}")

[[71 94 83 34 16]
 [26 84 49 24 88]
 [48 19 79 23 97]
 [41 76 34 21 46]]
Shape of the array:
 (4, 5)


In [27]:
# dimenation of the array
x.ndim

2

In [28]:
# number of the element present in the array
x.size

20

In [29]:
#checking the datatype of the element in the array
x.dtype

dtype('int32')

In [30]:
myarr=np.random.randint(10,20,10)
print(myarr)

[17 11 19 11 16 11 14 12 14 10]


In [31]:
myarr.max()

19

In [32]:
# index location of max value
myarr.argmax()

2

In [33]:
myarr.min()

10

In [34]:
#index location of min value
myarr.argmin()

9

## Mathematical Opearation with NumPy array

In [35]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list1+list2 #==> instead of adding this PLus operator will concatenate the two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [36]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))
print(a)
print(b)

[[10 11 17]
 [13 14 18]
 [17 19 15]]
[[23 24 23]
 [27 29 27]
 [24 27 20]]


In [37]:
# let do some basic Mathematic Operations
print(a+b) #==> same result could be obtained by np.add(a,b)

[[33 35 40]
 [40 43 45]
 [41 46 35]]


In [38]:
print(a-b) #==> same result could be obtained by np.substract(a,b)

[[-13 -13  -6]
 [-14 -15  -9]
 [ -7  -8  -5]]


In [39]:
print(a*b) #==> same result could be obtained by np.multiply(a,b)

[[230 264 391]
 [351 406 486]
 [408 513 300]]


In [40]:
print(a/b) #==> same result could be obtained by np.division(a,b)

[[0.43478261 0.45833333 0.73913043]
 [0.48148148 0.48275862 0.66666667]
 [0.70833333 0.7037037  0.75      ]]


In [41]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
arr/arr

C:\Users\Admin\AppData\Local\Temp\ipykernel_9992\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [47]:
np.log(arr)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9992\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

- Since log of zero is infinity but still it giving result 

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr.min()

0

In [50]:
arr.max()

10

In [51]:
arr.mean()

5.0

In [52]:
arr.std()

3.1622776601683795

In [53]:
arr.var()

10.0

In [54]:
arr=np.random.randint(1,10,(5,5))
arr

array([[1, 3, 9, 8, 3],
       [4, 1, 1, 1, 5],
       [1, 4, 4, 8, 8],
       [9, 1, 9, 2, 8],
       [7, 1, 3, 8, 3]])

In [55]:
# summation across the rows
arr.sum(axis=0) 

array([22, 10, 26, 27, 27])

In [56]:
# summation across the column
arr.sum(axis=1)

array([24, 12, 25, 29, 22])

## Array Manipulation

In [57]:
array1=np.random.randint(10,20,(2,3))
print(array1)
array1.shape

[[19 10 15]
 [19 11 16]]


(2, 3)

In [58]:
# transpose
trans=np.transpose(array1)
print(trans)
trans.shape

[[19 19]
 [10 11]
 [15 16]]


(3, 2)

In [59]:
# reshaping array
a=np.random.randint(10,30,(2,3))
print(a)
print(a.shape)

[[25 16 29]
 [12 18 27]]
(2, 3)


In [60]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[25 16]
 [29 12]
 [18 27]]
(3, 2)


## Numpy Indexing and selection
- Grabbing single element
- Grabbing a slice of element
- Brodcasting selection
- Indexing and selection in two dimentions
- Condition Selection

## Grabbing single element

In [61]:
myarr=np.arange(0,11)
print(myarr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [62]:
myarr[3]

3

In [63]:
myarr[3:5] #==> five is excluding

array([3, 4])

In [64]:
myarr[:5]

array([0, 1, 2, 3, 4])

In [65]:
myarr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Brodcasting

In [66]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# it means you can reassign multiple values simultaneously
myarr[0:5]=100

In [68]:
myarr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## slicing

In [70]:
# slicing section of array and setting it to new variable
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
slice_of_array=arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [72]:
slice_of_array[:]=99
slice_of_array

array([99, 99, 99, 99, 99])

In [73]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [74]:
arr_copy=arr.copy()

In [75]:
arr_copy[:]=100

In [76]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [77]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## slicing 2D array

In [78]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [79]:
#negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


## indexing and selection in two dimentional array

In [80]:
arr_2d=np.random.randint(10,99,(3,3))
arr_2d

array([[21, 87, 18],
       [49, 92, 85],
       [29, 17, 83]])

In [81]:
arr_2d.shape

(3, 3)

In [82]:
# to grab first row
arr_2d[0]

array([21, 87, 18])

In [83]:
# to grab third element in the first row
arr_2d[0][2]

18

In [84]:
# to get some slice or subsection of matrix
arr_2d

array([[21, 87, 18],
       [49, 92, 85],
       [29, 17, 83]])

In [85]:
arr_2d[:2,1:]

array([[87, 18],
       [92, 85]])

In [86]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(f'2nd element on 1st row: {arr[0, 1]}')

2nd element on 1st row: 2


## Indexing in 3D array


In [87]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


## Condition and selection

In [88]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [90]:
bool_arr = arr > 4

In [91]:
arr[bool_arr] #==> filtering

array([ 5,  6,  7,  8,  9, 10])

In [92]:
# same result can be obtained by following code
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
print("="*100)