# NumPy 
NumPy is a Python library used for scientific computing and data analysis. It provides a powerful array object that allows you to efficiently work with large, multi-dimensional arrays and matrices of numerical data. 

NumPy array object is much more efficient than Python's built-in list object when it comes to handling large datasets, as it is implemented in C and provides vectorized operations that can be executed on the entire array at once, rather than iterating over each element one by one. 

NumPy also provides a wide range of mathematical functions that can be applied to arrays, such as trigonometric, logarithmic, and exponential functions, as well as tools for linear algebra, Fourier analysis, and random number generation. 

NumPy is an essential library for data scientists and scientific computing professionals, as it enables fast and efficient computation on large datasets in Python.

**(1) we can only represet 1D,2D and 3D array.** <br>
**(2) To know dimentions of array we use array.ndim** <br>
**(3) array.size gives the number of elements,size gives the number of rows and columns** <br>
**(4) To produce numbers in floating values is not possible from range() function so we use np.arange()to do so** <br>
**(5) I can easily do arithmetic operations with arrays slicing works like - array[row_start:row_end,column]** <br>
**(6) To do matrix multipication we use @ like - array1@array2** <br>
**(7) we cannot transpose single dimentional array** <br>
**(8) To convert a two dimentional array into one dimentional array.flatten() function is used.** <br>
**(9) To convert an one dimentional array into two dimentional array , np.expand_dims function is used** <br>
**(10) In numpy for string there everything is available in np.char.any_function this function**

In [1]:
import numpy as np

In [2]:
ar = [1,2,3,4,5]

In [3]:
ar

[1, 2, 3, 4, 5]

In [4]:
#array Syntax : np.array()
np.array(ar)

array([1, 2, 3, 4, 5])

In [5]:
np.array([ar,[6,7,8,4,5]])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 4, 5]])

In [6]:
print(type(ar))

<class 'list'>


In [7]:
# now we convert ar to array
asarry = np.asanyarray(ar)
print(type(asarry))

<class 'numpy.ndarray'>


## matrix is a subset of array.

In [8]:
matrix = np.matrix(ar)
matrix                  # matrix is by default is two dimentional

matrix([[1, 2, 3, 4, 5]])

In [9]:
#Convert matrix to array
np.asanyarray(matrix)      # this is not converted to array because matrix is already subset of array

matrix([[1, 2, 3, 4, 5]])

In [10]:
# to produce array we use some type of functions like....
def fromfunction(i,j):
    return i == j
print(np.fromfunction(fromfunction,(3,3)))

def fromfunction1(i,j):
    return i+j
np.fromfunction(fromfunction1,(10,5),dtype=int)


[[ True False False]
 [False  True False]
 [False False  True]]


array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]])

In [11]:
np.fromiter((i for i in range(5,10)),dtype=float)

array([5., 6., 7., 8., 9.])

In [12]:
np.fromstring('3,4,3,445,65,333,22, ',sep=',')

array([  3.,   4.,   3., 445.,  65., 333.,  22.,  -1.])

# Data types

In [13]:
# this is one dimentional
lst = [1,2,3,4,5]
arr = np.array(lst)
print("Dimension",arr.ndim)
print("Size",arr.size)
arr

Dimension 1
Size 5


array([1, 2, 3, 4, 5])

In [14]:
# this is two dimentional
lst2D = [[1,2,3,4,5],[1,2,3,4,5]]
arr2D = np.array(lst2D)
print("2D Array Dimension:",arr2D.ndim)
print("2D Array Size",arr2D.size)
print("2D Array Shape:",arr2D.shape)
arr2D

2D Array Dimension: 2
2D Array Size 10
2D Array Shape: (2, 5)


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

### To produce numbers in floating values is not possible from range() function so we use np.arange to do so.

In [15]:
(np.arange(0.3,9.6))

array([0.3, 1.3, 2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3])

In [16]:
(np.arange(0.5,10.5))

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [17]:
# to jump 
np.arange(0.3,10.3,.4)

array([0.3, 0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 3.9, 4.3, 4.7, 5.1,
       5.5, 5.9, 6.3, 6.7, 7.1, 7.5, 7.9, 8.3, 8.7, 9.1, 9.5, 9.9])

In [18]:
# to jump 
np.arange(0.5,10.5,.2)

array([ 0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,  2.3,  2.5,
        2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,  4.5,  4.7,
        4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,  6.7,  6.9,
        7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,  8.9,  9.1,
        9.3,  9.5,  9.7,  9.9, 10.1, 10.3])

## linSpace function

In [19]:
np.linspace(1,20,100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

## zeros function

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
zero= np.zeros((10,30))    # here are 10 rows and 30 columns
print(zero.shape)
zero

(10, 30)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [22]:
zeros= np.zeros((3,3,4))   # here are 3 matrixs or arrays of 3 rows and 4 columns
print("Shape:",zero.shape)
print("Dimension:",zeros.ndim)
zeros

Shape: (10, 30)
Dimension: 3


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## ones function

In [23]:
# one dimentional ones array or matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
# two dimentional ones array or matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# three dimentional ones array or matrix
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
# Wec can easily do arithmetic operations with arrays 
np.ones((2,4,4))* 3 + 32/2

array([[[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]],

       [[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]]])

# empty function

In [27]:
np.empty((8,7))   # these are less values

array([[1.37051133e-311, 1.37047758e-311, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.15998412e-028,
        4.31603868e-080],
       [1.94919985e-153, 1.35717430e+131, 6.96320218e-077,
        2.90699771e-033, 1.05133185e-153, 4.56340414e-072,
        6.76925730e-043],
       [1.05249722e-153, 2.99067252e-067, 1.57629445e-052,
        6.01347002e-154, 1.05220588e-153, 1.95996720e-062,
        3.67057129e-062],
       [1.05191454e-153, 1.95996719e-062, 8.54732020e-072,
        1.05162320e-153, 1.28448408e-057, 6.01391519e-154,
        2.90850235e-033],
       [1.05133186e-153, 8.41799484e-053, 6.77276055e-043,
        1.05249723e-153, 5.51681706e-048, 1.57711011e-052,
        1.05220589e-153],
       [1.81148477e-152, 3.61545994e-043, 3.67247041e-062,
        1.05191455e-153, 3.61550131e-043, 8.55174191e-072,
        1.05162321e-153],
       [2.36945492e-038, 2.91000698e-033, 1.02455592e+136,
        6.01347002e-154, 1.55284596e-033, 6.77626379e-043,
        1.05249724

# eye function

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random function

In [29]:
np.random.randn(3,4)  # this randn functions mean is always 0 and `std` is always 1

array([[ 0.86753092, -0.51840523, -2.0308927 , -2.45551997],
       [ 0.95633179, -0.18029133,  0.80262622,  1.68991338],
       [-0.09116482,  0.79913086,  0.25633353,  0.38722639]])

In [30]:
np.random.rand(2,3)   # this without anything produces the data

array([[0.02432486, 0.31368692, 0.16537142],
       [0.12831753, 0.10504874, 0.56712348]])

In [31]:
np.random.randint(1,20,size=20)

array([10,  3, 10, 14, 14, 16, 12,  5, 18,  1, 13, 15, 18, 11, 19, 14,  4,
       18, 11,  6])

In [32]:
arr_randint =np.random.randint(1,20,size=(10,20))

In [33]:
arr_randint

array([[15, 19,  5,  3,  3,  1, 18,  1, 12,  5,  8,  1,  7, 10, 18,  6,
        19,  3, 17,  6],
       [ 9,  9,  4, 11,  3,  1,  9, 19,  3,  5, 13, 12,  5, 16, 17,  7,
        12, 15, 12,  3],
       [15, 11,  5, 11,  5, 13, 14, 12,  6, 16, 12, 19,  1,  7, 12, 11,
        11,  5, 19,  7],
       [19,  9,  4,  7,  6, 15,  6,  4, 14, 19, 13, 10, 17,  4, 10,  4,
         5,  8,  7,  5],
       [ 6,  8, 19,  1,  3, 18, 15,  9,  7,  1,  9, 15, 16, 11, 13, 16,
         7,  7,  1,  5],
       [16,  5, 12,  4, 13, 16,  2, 19, 17,  2,  1, 11, 17, 17, 11,  5,
         5,  9, 14,  1],
       [17,  6,  5, 10, 15, 18,  8,  2, 13,  1,  6, 19,  5, 18, 12, 15,
         1, 13, 18,  7],
       [ 2,  8,  6, 15, 11,  4, 18, 14,  9, 17,  2,  5,  7,  3, 17,  9,
        13,  2,  9, 11],
       [ 9, 11, 15, 13, 17, 16,  3, 17,  3, 19, 15, 15, 15,  3, 16, 15,
        11, 15, 11, 16],
       [ 3, 15, 15,  7,  2,  8,  9, 11, 14, 10, 17, 13, 10,  7,  3, 14,
         9, 11, 18,  7]])

In [34]:
# reshaping my data
arr_randint.reshape(1,200)

array([[15, 19,  5,  3,  3,  1, 18,  1, 12,  5,  8,  1,  7, 10, 18,  6,
        19,  3, 17,  6,  9,  9,  4, 11,  3,  1,  9, 19,  3,  5, 13, 12,
         5, 16, 17,  7, 12, 15, 12,  3, 15, 11,  5, 11,  5, 13, 14, 12,
         6, 16, 12, 19,  1,  7, 12, 11, 11,  5, 19,  7, 19,  9,  4,  7,
         6, 15,  6,  4, 14, 19, 13, 10, 17,  4, 10,  4,  5,  8,  7,  5,
         6,  8, 19,  1,  3, 18, 15,  9,  7,  1,  9, 15, 16, 11, 13, 16,
         7,  7,  1,  5, 16,  5, 12,  4, 13, 16,  2, 19, 17,  2,  1, 11,
        17, 17, 11,  5,  5,  9, 14,  1, 17,  6,  5, 10, 15, 18,  8,  2,
        13,  1,  6, 19,  5, 18, 12, 15,  1, 13, 18,  7,  2,  8,  6, 15,
        11,  4, 18, 14,  9, 17,  2,  5,  7,  3, 17,  9, 13,  2,  9, 11,
         9, 11, 15, 13, 17, 16,  3, 17,  3, 19, 15, 15, 15,  3, 16, 15,
        11, 15, 11, 16,  3, 15, 15,  7,  2,  8,  9, 11, 14, 10, 17, 13,
        10,  7,  3, 14,  9, 11, 18,  7]])

In [35]:
arr1 = np.random.randint(1,100,size=(4,4))
arr1

array([[69, 90, 38, 76],
       [85, 78, 76, 30],
       [12, 61, 72, 76],
       [59,  2, 10, 12]])

## indexing and slicing
this works like - array[row_start:row_end,column]

In [36]:
# i wanna to get our 7 by indexing
print(arr1[0][3])
arr1

76


array([[69, 90, 38, 76],
       [85, 78, 76, 30],
       [12, 61, 72, 76],
       [59,  2, 10, 12]])

In [37]:
arr1[:,3]

array([76, 30, 76, 12])

In [38]:
#indexing
arr1[1:,1]

array([78, 61,  2])

In [39]:
arr2 = np.random.randint(1,300,(5,6))
arr2

array([[122, 191,  29, 189, 116,  68],
       [299, 201,  85, 155, 157, 281],
       [287, 159, 110, 159,  47,  75],
       [ 69, 193, 192, 269, 290, 228],
       [ 39,  12, 167, 172, 252,  90]])

In [40]:
arr3 = arr2 > 200

In [41]:
arr3

array([[False, False, False, False, False, False],
       [ True,  True, False, False, False,  True],
       [ True, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [False, False, False, False,  True, False]])

In [42]:
arr3[arr2 > 200]

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [43]:
arr2[arr3]     # finnaly I brought data by my self which is greater than 200

array([299, 201, 281, 287, 269, 290, 228, 252])

In [44]:
# array for matrix multiplication
arr_mul1 = np.random.randint(1,4,(3,3))
arr_mul2 = np.random.randint(4,7,(3,4))

In [45]:
arr_mul1

array([[3, 3, 3],
       [1, 2, 2],
       [3, 2, 3]])

In [46]:
arr_mul2

array([[5, 4, 6, 5],
       [5, 6, 6, 4],
       [5, 5, 6, 4]])

In [47]:
arr_mul1 @ arr_mul2

array([[45, 45, 54, 39],
       [25, 26, 30, 21],
       [40, 39, 48, 35]])

# brodcasting
In this method we do any operations with complete row or column

In [48]:
arr_brodcast = np.random.randint(1,10,(4,4))

In [49]:
arr_brodcast

array([[1, 6, 3, 1],
       [8, 5, 4, 5],
       [1, 8, 6, 8],
       [6, 3, 7, 9]])

In [50]:
arr_to_add = np.array([1,2,3,4])

In [51]:
arr_to_add 

array([1, 2, 3, 4])

In [52]:
arr_brodcast + arr_to_add

array([[ 2,  8,  6,  5],
       [ 9,  7,  7,  9],
       [ 2, 10,  9, 12],
       [ 7,  5, 10, 13]])

In [53]:
arr_to_add_col = np.array([[1,2,3,4]]).T  # transpose
arr_to_add_col

array([[1],
       [2],
       [3],
       [4]])

In [54]:
arr_brodcast + arr_to_add_col

array([[ 2,  7,  4,  2],
       [10,  7,  6,  7],
       [ 4, 11,  9, 11],
       [10,  7, 11, 13]])

## other functions

In [55]:
arr_other= np.random.randint(1,10,(4,4))
arr_other

array([[1, 7, 4, 5],
       [6, 5, 4, 4],
       [5, 9, 6, 5],
       [8, 5, 4, 2]])

In [56]:
np.square(arr_other)

array([[ 1, 49, 16, 25],
       [36, 25, 16, 16],
       [25, 81, 36, 25],
       [64, 25, 16,  4]], dtype=int32)

In [57]:
np.sqrt(arr_other)

array([[1.        , 2.64575131, 2.        , 2.23606798],
       [2.44948974, 2.23606798, 2.        , 2.        ],
       [2.23606798, 3.        , 2.44948974, 2.23606798],
       [2.82842712, 2.23606798, 2.        , 1.41421356]])

In [58]:
np.exp2(arr_other)

array([[  2., 128.,  16.,  32.],
       [ 64.,  32.,  16.,  16.],
       [ 32., 512.,  64.,  32.],
       [256.,  32.,  16.,   4.]])

In [59]:
np.exp(arr_other)

array([[2.71828183e+00, 1.09663316e+03, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.48413159e+02, 5.45981500e+01, 5.45981500e+01],
       [1.48413159e+02, 8.10308393e+03, 4.03428793e+02, 1.48413159e+02],
       [2.98095799e+03, 1.48413159e+02, 5.45981500e+01, 7.38905610e+00]])

In [60]:
np.log2(arr_other)

array([[0.        , 2.80735492, 2.        , 2.32192809],
       [2.5849625 , 2.32192809, 2.        , 2.        ],
       [2.32192809, 3.169925  , 2.5849625 , 2.32192809],
       [3.        , 2.32192809, 2.        , 1.        ]])

In [61]:
np.log10(arr_other)

array([[0.        , 0.84509804, 0.60205999, 0.69897   ],
       [0.77815125, 0.69897   , 0.60205999, 0.60205999],
       [0.69897   , 0.95424251, 0.77815125, 0.69897   ],
       [0.90308999, 0.69897   , 0.60205999, 0.30103   ]])

# Array manipulation

In [62]:
array = np.random.randint(1,10,(3,4))
array

array([[6, 3, 4, 5],
       [5, 9, 7, 5],
       [2, 9, 7, 7]])

In [63]:
# changing number of rows and columns we can only reshape this of multiplication of 12
print(array.reshape(2,6))
print('another array  : ',array.reshape(1,12))
print('another array2 : ',array.reshape(12,1))
print('another array3 : ',array.reshape(4,3))
print('another array4 : ',array.reshape(4,3))

[[6 3 4 5 5 9]
 [7 5 2 9 7 7]]
another array  :  [[6 3 4 5 5 9 7 5 2 9 7 7]]
another array2 :  [[6]
 [3]
 [4]
 [5]
 [5]
 [9]
 [7]
 [5]
 [2]
 [9]
 [7]
 [7]]
another array3 :  [[6 3 4]
 [5 5 9]
 [7 5 2]
 [9 7 7]]
another array4 :  [[6 3 4]
 [5 5 9]
 [7 5 2]
 [9 7 7]]


# flatten function

In [64]:
array.flatten()

array([6, 3, 4, 5, 5, 9, 7, 5, 2, 9, 7, 7])

# expand_dims function

In [65]:
arr_expandDim = np.random.randint(1,10,20)
arr_expandDim

array([4, 2, 2, 8, 3, 7, 7, 8, 6, 4, 2, 2, 1, 5, 4, 1, 8, 9, 5, 4])

In [66]:
np.expand_dims(arr_expandDim, axis=0)

array([[4, 2, 2, 8, 3, 7, 7, 8, 6, 4, 2, 2, 1, 5, 4, 1, 8, 9, 5, 4]])

In [67]:
np.expand_dims(arr_expandDim, axis=1)

array([[4],
       [2],
       [2],
       [8],
       [3],
       [7],
       [7],
       [8],
       [6],
       [4],
       [2],
       [2],
       [1],
       [5],
       [4],
       [1],
       [8],
       [9],
       [5],
       [4]])

## repeat function
this repeats each element as the value we give

In [68]:
arr_repeat = np.random.randint(1,10,5)
arr_repeat

array([3, 2, 7, 3, 2])

In [69]:
np.repeat(arr_repeat,4)

array([3, 3, 3, 3, 2, 2, 2, 2, 7, 7, 7, 7, 3, 3, 3, 3, 2, 2, 2, 2])

# roll function
this rolls the array as the value we give to shift

In [70]:
arr_roll = np.random.randint(1,10,6)
arr_roll


array([4, 1, 5, 2, 1, 9])

In [71]:
np.roll(a=arr_roll,shift=2)

array([1, 9, 4, 1, 5, 2])

# diag function
In this we gives a single dimentional array and this make 2D array and that arrays value assign to dialgonal

In [72]:
arr_diag = np.random.randint(1,10,6)
arr_diag

array([3, 6, 9, 8, 4, 8])

# String Functions

In [73]:
arr_str = np.array([['sunil','mangal','shahaji','zambare']])
arr_str

array([['sunil', 'mangal', 'shahaji', 'zambare']], dtype='<U7')

In [74]:
np.char.encode(arr_str)

array([[b'sunil', b'mangal', b'shahaji', b'zambare']], dtype='|S7')

In [75]:
end=np.char.endswith(arr_str,'sunil')
arr_str[end]

array(['sunil'], dtype='<U7')

In [76]:
np.char.upper(arr_str)

array([['SUNIL', 'MANGAL', 'SHAHAJI', 'ZAMBARE']], dtype='<U7')

In [77]:
np.char.capitalize(arr_str)

array([['Sunil', 'Mangal', 'Shahaji', 'Zambare']], dtype='<U7')

# Mathematical functions

In [78]:
arr_maths = np.random.randint(1,10,(3,3))
arr_maths

array([[8, 9, 1],
       [6, 5, 9],
       [5, 7, 8]])

In [79]:
np.sin(arr_maths)

array([[ 0.98935825,  0.41211849,  0.84147098],
       [-0.2794155 , -0.95892427,  0.41211849],
       [-0.95892427,  0.6569866 ,  0.98935825]])

In [80]:
np.cos(arr_maths)

array([[-0.14550003, -0.91113026,  0.54030231],
       [ 0.96017029,  0.28366219, -0.91113026],
       [ 0.28366219,  0.75390225, -0.14550003]])

In [81]:
np.power(arr_maths,2)

array([[64, 81,  1],
       [36, 25, 81],
       [25, 49, 64]], dtype=int32)

In [82]:
np.mean(arr_maths)

6.444444444444445

In [83]:
np.median(arr_maths)

7.0

In [84]:
np.var(arr_maths)

5.802469135802469

In [85]:
np.std(arr_maths)

2.4088314876309775

In [86]:
np.min(arr_maths)

1

In [87]:
np.max(arr_maths)

9

# sort, search and count function

In [88]:
arr_sort_search_count = np.array(np.random.randint(1,20,12))
arr_sort_search_count

array([ 2,  4, 10,  2,  8, 12, 14, 12,  6, 16,  6,  5])

In [89]:
np.sort(arr_sort_search_count)

array([ 2,  2,  4,  5,  6,  6,  8, 10, 12, 12, 14, 16])

In [90]:
arr_sort_search_count.shape

(12,)

In [91]:
np.searchsorted(arr_sort_search_count,3444)   #because I have 12 elements and these are in 0-11 index

12

# count nonzero fuction
this counts how many non zero values are in my data

In [92]:
arr_countNonZero = np.array([1,2,343,0,6,0,0,0,3434,0,767])
arr_countNonZero

array([   1,    2,  343,    0,    6,    0,    0,    0, 3434,    0,  767])

In [93]:
np.count_nonzero(arr_countNonZero)

6

# where function
this function returns value with position(index)

In [94]:
arr_where = np.array([1,2,343,0,6,0,0,0,3434,0,767])
np.where(arr_where== 0)

(array([3, 5, 6, 7, 9], dtype=int64),)

# extract function
this extracts Or take out as per given condition

In [95]:
arr_extract = np.array([1,2,343,0,6,0,0,0,3434,0,767])
np.extract(arr_extract > 0, arr_extract)

array([   1,    2,  343,    6, 3434,  767])

# matrix library

In [96]:
import numpy.matlib as npm

In [97]:
npm.zeros(7)

matrix([[0., 0., 0., 0., 0., 0., 0.]])

In [98]:
npm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
npm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Linear Algebra

In [100]:
linear_arr1 =np.random.randint(2,10,(2,2))
linear_arr2 =np.random.randint(2,10,(2,2))
linear_arr1

array([[6, 5],
       [8, 3]])

In [101]:
linear_arr2

array([[2, 8],
       [7, 5]])

In [102]:
np.dot(linear_arr1,linear_arr2)

array([[47, 73],
       [37, 79]])