## Importing Numpy library with alias name np

In [1]:
import numpy as np

## 1.Create zero dimensional array

In [2]:
zero_dimensional_array = np.array(42)

In [3]:
print(zero_dimensional_array)

42


## 2.Create one dimensional array

In [4]:
one_dimensional_array = np.array([1, 2, 3])

In [5]:
print(one_dimensional_array)

[1 2 3]


## 3.Create two-dimensional array

In [6]:
two_dim_array = np.array([[1, 2],[3,4]])

In [7]:
two_dim_array

array([[1, 2],
       [3, 4]])

## 4.Create three-dimensional array:

In [8]:
three_dim_array = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

In [9]:
three_dim_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## 5.Check Number of dimensions ?

In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 6.Uninitialized

In [13]:
ar = np.empty([5, 3], dtype = int)

In [14]:
ar

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,    1400,       0],
       [      0, 4980828,       0]])

In [15]:
print(ar)

[[      0       0       0]
 [      0       0       0]
 [      0       0       0]
 [      0    1400       0]
 [      0 4980828       0]]


## 7.Initialized with zeros

In [16]:
a = np.zeros([3, 3]) #default dtype float

In [17]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 8.Initialized with ones

In [19]:
maximum_list = np.ones(5)

In [20]:
maximum_list

array([1., 1., 1., 1., 1.])

## 9.To create ones 2d Dimensional Array

In [21]:
max_lst = np.ones((3,4))

In [22]:
max_lst

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 10.Array from specified numbers

In [23]:
a1 = np.full([3, 3],30)

In [24]:
print(a1)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


## 11.To create an identity matrix.

In [25]:
a2 = np.identity(3)

In [26]:
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12.Creating ndarray with existing data(list to ndarray)

In [27]:
list1 = [1, 2, 3, 4, 5]

In [28]:
ar = np.asarray(list1)

In [29]:
print(ar)

[1 2 3 4 5]


## 13.Tuple to Ndarray

In [30]:
tuple1 =(1, 2, 3, 4, 5)

In [31]:
ar1 = np.asarray(tuple1)

In [32]:
ar1

array([1, 2, 3, 4, 5])

## 14.Array from numerical ranges

In [34]:
array_arrange = np.arange(5)

In [35]:
array_arrange

array([0, 1, 2, 3, 4])

In [36]:
another_array = np.arange(10,20,2)

In [37]:
another_array

array([10, 12, 14, 16, 18])

## 15.To change the type

In [38]:
max_list = np.ones([3, 4], dtype = int)

In [39]:
max_list

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
max_list1 = np.ones([3, 4], dtype = bool)

In [41]:
max_list1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## 16.Access 1-D Arrays : Get the first element from the array

In [42]:
arr = np.array([1, 2, 3, 4, 5])

In [43]:
arr

array([1, 2, 3, 4, 5])

In [44]:
print(arr[0])

1


In [45]:
#Get the second element from the array
print(arr[1])

2


In [46]:
#Get the third and fourth element from the array
print(arr[2] + arr[3])

7


## 17.Access 2-D Arrays

In [48]:
arr1 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

In [49]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
print(f"Second element on fist dimension: {arr1[0, 1]}")

Second element on fist dimension: 2


In [55]:
#Access the 5th element on 1st dimension
arr2 = np.array([[1, 2, 5, 7, 9],[11, 24, 35, 45, 95]])

In [56]:
arr2

array([[ 1,  2,  5,  7,  9],
       [11, 24, 35, 45, 95]])

In [58]:
print(f'5th element on 2nd dimension: {arr2[1, 4]}')

5th element on 2nd dimension: 95


## 18.Access 3-D Arrays
### Access the third element of the second array of the first array

In [60]:
arr3 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

In [61]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
print(arr3[0, 1, 2])

6


# 19.Negative Indexing:
### Use negative indexing to access an array from the end.

In [63]:
new_arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

In [64]:
new_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
print(f'Last element from 2nd dim: {new_arr[1, -1]}')

Last element from 2nd dim: 10


## 20.Slicing in python means taking elements from one given index to another given                   index

In [67]:
max_slicing =np.arange(1, 101).reshape(10,10)

In [68]:
max_slicing

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [69]:
#Access the Element
acess_ele = max_slicing[2, 6]

In [70]:
acess_ele

27

In [72]:
#Access the whole Row
acess_e1 = max_slicing[2]

In [73]:
acess_e1

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [74]:
#Access the column (But in row format)
acess_e2 = max_slicing[:,0]
print(acess_e2)

[ 1 11 21 31 41 51 61 71 81 91]


In [76]:
#Access the columns
acess_e3 = max_slicing[:,0 : 2]

In [77]:
acess_e3

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [79]:
#Slice some part of an array
acess_e4 = max_slicing[1:4, 1:4]

In [80]:
acess_e4

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [82]:
#Access the whole matrix:
# There are three ways to access the print the whole matrix
acess_new = max_slicing[:]
print(acess_new)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [83]:
acess_new1 = max_slicing[::]
print(acess_new1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [84]:
acess_new2 = max_slicing[:,:]
print(acess_new2)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


# 21.Concatenate: Create an two array to concatenate them.

In [86]:
concat_1 = np.arange(1, 17).reshape(4, 4)
concat_2 = np.arange(17,33).reshape(4, 4)

In [87]:
print(concat_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [88]:
print(concat_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [90]:
#Concatenate Columnwise
concat_col = np.concatenate((concat_1,concat_2))

In [91]:
print(concat_col)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [92]:
concat_1 = np.vstack((concat_1, concat_2))
print(concat_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [94]:
#Concatenate Row wise
concat_ = np.concatenate((concat_1,concat_2), axis=0)
print(concat_)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


## 22.Checking the Data Type of an Array

In [101]:
data_type = np.array([1, 2, 3, 4, 5])

In [102]:
print(data_type)

[1 2 3 4 5]


In [103]:
print(data_type.dtype)

int32


## 23.Creating Arrays with a Defined Data Type

In [104]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## 24.Converting Data Type on Existing Arrays

In [105]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 2 3]
int32


## 25.COPY: Make a copy, change the original array, and display both arrays

In [106]:
disp_arr = np.array([1, 2, 3, 4, 5])

In [107]:
copy_arr = disp_arr.copy()

In [108]:
disp_arr[0] = 99

In [110]:
print(disp_arr)

[99  2  3  4  5]


In [111]:
print(copy_arr)

[1 2 3 4 5]


## 26.VIEW: Make a view, change the original array, and display both arrays

In [113]:
original_arr = np.array([10, 20, 30, 40, 50])
view_array = original_arr.view()
original_arr[0] = 75
print(original_arr)
print(view_array)

[75 20 30 40 50]
[75 20 30 40 50]


In [114]:
#Make Changes in the VIEW
new_arr = np.array([10, 20, 30, 40, 50])
view_arr = new_arr.view()
new_arr[0] = 100
print(new_arr)
print(view_arr)

[100  20  30  40  50]
[100  20  30  40  50]


## 27.NumPy Array Shape

In [115]:
arr_ele = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr_ele.shape)

(2, 4)


## 28.NumPy Array Reshaping

#### Reshape From 1-D to 2-D: Reshaping Converting the following 1-D array with 12 elements into a 2-D  array.
#### The outermost dimension will have 4 arrays, each with 3 elements

In [116]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr1.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 29.Reshape From 1-D to 3-D:Convert the following 1-D array with 12 elements into a 3-D array.
#### The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

In [117]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## 30.Unknown Dimension

In [118]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# 31.Flattening the arrays:
#### Flattening array means converting a multidimensional array into a 1D array.We can use reshape(-1) to do this. 
#### Convert the array into a 1D array

In [119]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## 32.NumPy transpose Array

In [120]:
# Create a 2 D Array
simple_array = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{simple_array}")
print(f" \n The shape of the array is {simple_array.shape}")

The defined array is 
[[33 14]
 [27 30]
 [30 25]
 [26 11]
 [20 33]
 [15 14]
 [28 39]
 [44 28]]
 
 The shape of the array is (8, 2)


## 33.Storing the transpose in another matrix object

In [121]:
simple_array = np.array(np.random.randint(10,45,(8,2)))
transpose_array =np.transpose(simple_array)
print(f" The transpose of the array is \n{transpose_array}")
print(f" \n The shape of the array is {transpose_array.shape}")

 The transpose of the array is 
[[24 42 43 36 35 32 31 42]
 [11 39 40 41 40 34 38 15]]
 
 The shape of the array is (2, 8)


## 34.NumPy Joining Array

In [122]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr = np.concatenate((arr1, arr2, arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


## 35.Join two 2-D arrays along rows (axis = 1)

In [123]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## 36.Joining Arrays Using Stack Functions

In [124]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


## 37.NumPy Splitting Array
#### Splitting 1-D Arrays:Split the array in 3 parts

In [125]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [126]:
#Split the array in 4 parts
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## 38.Access the splitted arrays

In [128]:
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [129]:
#Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


## 39.NumPy Searching Arrays:Find the indexes where the value is 4

In [130]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [131]:
#Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


# 40.NumPy Sorting Arrays

In [132]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [133]:
#sort arrays of strings, or any other data type
arr = np.array(['banana', 'cherry', 'apple','pineaapple','kivi','strawberry','dgragon fruit'])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'dgragon fruit' 'kivi' 'pineaapple'
 'strawberry']


## 41.Random Numbers in Numpy

In [134]:
# Generate a random integer from 0 to 100:
from numpy import random
x = random.randint(100)
print(x)

64


In [135]:
#Generate a random float from 0 to 1
from numpy import random
x = random.rand()
print(x)

0.3151457659597129


### 42.Generate a 1-D array containing 5 random integers from 0 to 100:

In [136]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[ 4  2 50 22 95]


### 43.Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

In [137]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[ 5 10 65 74 52]
 [84 17  0 41 17]
 [44 28 30 48 57]]


### 44.Generate a 1-D array containing 5 random floats

In [138]:
from numpy import random
x = random.rand(5)
print(x)

[0.31564773 0.2547086  0.15097067 0.78500535 0.02254881]


### 45.Generate a 2-D array with 3 rows, each row containing 5 random numbers

In [139]:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.21829869 0.61208228 0.05962958 0.88456292 0.9288773 ]
 [0.27300915 0.93103491 0.0080123  0.26649639 0.08642834]
 [0.03486469 0.37145705 0.17996353 0.09757602 0.23184347]]


## 46.Generate Random Number From Array using choice method

In [140]:
#Return one of the values in an array:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

7


### 47.Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [141]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 5 3 3 7]
 [9 5 7 7 7]
 [7 7 9 5 9]]


## 48.Simple Arithmetic

In [142]:
arr_1 = np.arange(1,10).reshape(3,3)
arr_2 = np.arange(1,10).reshape(3,3)
print(arr_1)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Method 1:Addition

In [143]:
add_1 = arr_1 + arr_2
print(add_1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Method 2:Addition

In [144]:
add_2 = np.add(arr_1,arr_2)
print(add_2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Subtraction:Method1

In [145]:
sub_1 = arr_1 - arr_2
print(sub_1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Subtraction:Method2

In [147]:
sub_2 = np.subtract(arr_1,arr_2)
print(sub_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Division:Method1

In [148]:
div_1 = arr_1 / arr_2
print(div_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Division:Method2

In [150]:
div_2 = np.divide(arr_1,arr_2)
print(div_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Multiplication:Method1

In [151]:
multi_1 = arr_1 * arr_2
print(multi_1)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## Multiplication:Method2

In [152]:
multi_2 = np.multiply(arr_1, arr_2)
print(multi_2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## Product:Method1

In [154]:
prod = arr_1 @ arr_2
print(prod)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Product:Method2

In [155]:
prod_2 = arr_1.dot(arr_2)
print(prod_2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## 49.Power:Raise the values in arr1 to the power of values in arr2

In [157]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


### 50.Remainder: mod() and the remainder() functions return the remainder of the  values in the first array                  corresponding to the values in the second array, and  return the results in a new array

In [158]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [159]:
newarr = np.remainder(arr1, arr2)
print(newarr)

[ 1  6  3  0  0 27]


In [160]:
#Quotient and Mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


## 51.Rounding Decimals

In [161]:
#Truncate elements of following array
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [162]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [163]:
#Rounding:Round off 3.1666 to 2 decimal places.
arr = np.around(3.1666, 2)
print(arr)

3.17


In [164]:
#Floor:The floor() function rounds off decimal to nearest lower integer
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [165]:
#Ceil:The ceil() function rounds off decimal to nearest upper integer
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]
